<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60a20b9d84b28',
	'title' => 'Convertr Sync Options',
	'fields' => array(
		array(
			'key' => 'field_60a4b96d84981',
			'label' => 'Force Update',
			'name' => 'force_update',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'If this set to \'Yes\' then the existing whitepapers will be updated on sync. This includes title, body, featured image, and vendor. Topic, whitepaper type, and company profile cannot be pulled automatically so they will be left untouched.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'style' => '',
		),
		array(
			'key' => 'field_60a2100ec3258',
			'label' => 'Campaigns',
			'name' => 'convertr_campaigns',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Add all currently active Convertr campaigns here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 0,
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => 'field_60a210e9c3259',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Campaign',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_60a210e9c3259',
					'label' => 'Name',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_60a2100ec3258',
				),
				array(
					'key' => 'field_60a2114dc325a',
					'label' => 'ID',
					'name' => 'id',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_60a2100ec3258',
				),
				array(
					'key' => 'field_60a21188c325b',
					'label' => 'API Key',
					'name' => 'api_key',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Campaign API Key which can be found on the campaign\'s setup page at the bottom.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_60a2100ec3258',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-sync-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'show_in_graphql' => 0,
	'graphql_field_name' => 'whitepaperSyncSettings',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1713451841,
));

endif;