<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6100e1ff8ea9b',
	'title' => 'Inline Ad Settings',
	'fields' => array(
		array(
			'key' => 'field_6100fea589d3a',
			'label' => 'Ads',
			'name' => 'ads',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'acfe_repeater_stylised_button' => 1,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Ad',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6100e2605b6b8',
					'label' => 'Admin Title',
					'name' => 'admin_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_6100fea589d3a',
				),
				array(
					'key' => 'field_6100e288ee315',
					'label' => 'Ad Unit Name',
					'name' => 'ad_unit_name',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'choices' => array(
						'box' => 'box',
						'boxInline' => 'boxInline',
						'datapoint' => 'datapoint',
						'leaderboard' => 'leaderboard',
						'leaderboardInline' => 'leaderboardInline',
						'mobileAnchor' => 'mobileAnchor',
						'mobileBox' => 'mobileBox',
						'native' => 'native',
						'nativePortal' => 'nativePortal',
						'prestitial' => 'prestitial',
						'skin' => 'skin',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'max' => '',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'prepend' => '',
					'append' => '',
					'required_message' => '',
					'allow_null' => 0,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'min' => '',
					'parent_repeater' => 'field_6100fea589d3a',
				),
				array(
					'key' => 'field_64d08784ae0d4',
					'label' => 'Application',
					'name' => 'application',
					'aria-label' => '',
					'type' => 'acfe_taxonomy_terms',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'taxonomy' => array(
						0 => 'applications',
					),
					'allow_terms' => '',
					'allow_level' => '',
					'field_type' => 'select',
					'default_value' => array(
					),
					'return_format' => 'object',
					'ui' => 1,
					'allow_null' => 0,
					'search_placeholder' => '',
					'multiple' => 0,
					'ajax' => 1,
					'save_terms' => 0,
					'load_terms' => 0,
					'populate_parental_terms' => 0,
					'display_hierarchical' => 0,
					'choices' => array(
					),
					'placeholder' => '',
					'layout' => '',
					'toggle' => 0,
					'allow_custom' => 0,
					'other_choice' => 0,
					'min' => '',
					'max' => '',
					'parent_repeater' => 'field_6100fea589d3a',
				),
				array(
					'key' => 'field_66a22ba0ebd02',
					'label' => 'Targeting ID',
					'name' => 'targeting_id',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'choices' => array(
						'inline' => 'inline',
						'top' => 'top',
						'top-right' => 'top-right',
						'left' => 'left',
						'right' => 'right',
						'bottom' => 'bottom',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'max' => '',
					'allow_custom' => 1,
					'search_placeholder' => '',
					'prepend' => '',
					'append' => '',
					'allow_null' => 1,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'min' => '',
					'parent_repeater' => 'field_6100fea589d3a',
				),
				array(
					'key' => 'field_6100e342ee316',
					'label' => 'SID (targeting options; not supported)',
					'name' => 'sid',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'choices' => array(
						'home' => 'home',
						'Reviews' => 'Reviews',
						'Security_News' => 'Security_News',
						'SW Labs' => 'SW Labs',
						'Women_in_IT_Security' => 'Women_in_IT_Security',
						'Women_in_Security_2020' => 'Women_in_Security_2020',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'max' => '',
					'allow_custom' => 1,
					'placeholder' => '',
					'search_placeholder' => '',
					'prepend' => '',
					'append' => '',
					'allow_null' => 1,
					'ui' => 1,
					'ajax' => 0,
					'min' => '',
					'parent_repeater' => 'field_6100fea589d3a',
				),
				array(
					'key' => 'field_6100e3f0ee317',
					'label' => 'Position (After Paragraph)',
					'name' => 'position',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '0-50',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'default_value' => 4,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => 50,
					'step' => 1,
					'parent_repeater' => 'field_6100fea589d3a',
				),
				array(
					'key' => 'field_6100f01f2a9c5',
					'label' => 'Basic Filters',
					'name' => 'basic_filters',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'layout' => 'block',
					'acfe_group_modal' => 1,
					'acfe_group_modal_close' => 1,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
					'acfe_seamless_style' => 0,
					'parent_repeater' => 'field_6100fea589d3a',
					'sub_fields' => array(
						array(
							'key' => 'field_6100f0a82a9c6',
							'label' => 'Taxonomy Query',
							'name' => 'taxonomy_query',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'layout' => 'block',
							'acfe_seamless_style' => 1,
							'acfe_group_modal' => 0,
							'acfe_group_modal_close' => 0,
							'acfe_group_modal_button' => '',
							'acfe_group_modal_size' => 'large',
							'sub_fields' => array(
								array(
									'key' => 'field_60ee6569839f6',
									'label' => 'Relation',
									'name' => 'relation',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'show_in_graphql' => 1,
									'choices' => array(
										'AND' => 'AND',
										'OR' => 'OR',
									),
									'default_value' => 'OR',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 1,
									'ajax' => 0,
									'return_format' => 'value',
									'allow_custom' => 0,
									'search_placeholder' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
								),
								array(
									'key' => 'field_60ee65e4839f7',
									'label' => 'Query Array',
									'name' => 'query_array',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'show_in_graphql' => 1,
									'acfe_repeater_stylised_button' => 0,
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'table',
									'button_label' => 'Add Query',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_60ee661c839f8',
											'label' => 'Terms',
											'name' => 'terms',
											'aria-label' => '',
											'type' => 'acfe_taxonomy_terms',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'show_in_graphql' => 1,
											'taxonomy' => array(
												0 => 'company_profile_type',
												1 => 'topic',
												2 => 'brand',
												3 => 'editorial_type',
												4 => 'industry',
												5 => 'whitepaper_type',
												6 => 'learning_type',
												7 => 'region',
												8 => 'podcast_show',
											),
											'allow_terms' => '',
											'allow_level' => '',
											'field_type' => 'select',
											'default_value' => array(
											),
											'return_format' => 'object',
											'ui' => 1,
											'allow_null' => 0,
											'placeholder' => '',
											'multiple' => 1,
											'ajax' => 0,
											'save_terms' => 0,
											'load_terms' => 0,
											'choices' => array(
											),
											'layout' => '',
											'toggle' => 0,
											'allow_custom' => 0,
											'other_choice' => 0,
											'search_placeholder' => '',
											'min' => '',
											'max' => '',
											'parent_repeater' => 'field_60ee65e4839f7',
										),
										array(
											'key' => 'field_60ee664c839f9',
											'label' => 'Operator',
											'name' => 'operator',
											'aria-label' => '',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'show_in_graphql' => 1,
											'choices' => array(
												'IN' => 'IN',
												'NOT IN' => 'NOT IN',
											),
											'default_value' => 'IN',
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'return_format' => 'value',
											'ajax' => 0,
											'placeholder' => '',
											'allow_custom' => 0,
											'search_placeholder' => '',
											'prepend' => '',
											'append' => '',
											'min' => '',
											'max' => '',
											'parent_repeater' => 'field_60ee65e4839f7',
										),
									),
								),
							),
						),
						array(
							'key' => 'field_6100f2772a9c7',
							'label' => 'Post Type',
							'name' => 'post_type',
							'aria-label' => '',
							'type' => 'acfe_post_types',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'post_type' => array(
								0 => 'company_profile',
								1 => 'editorial',
								2 => 'learning',
								3 => 'people',
								4 => 'product_profile',
								5 => 'whitepaper',
							),
							'field_type' => 'select',
							'default_value' => array(
							),
							'return_format' => 'name',
							'allow_null' => 1,
							'multiple' => 1,
							'ui' => 1,
							'ajax' => 0,
							'placeholder' => '',
							'search_placeholder' => '',
							'allow_custom' => 0,
							'choices' => array(
							),
							'layout' => '',
							'toggle' => 0,
							'other_choice' => 0,
							'min' => '',
							'max' => '',
						),
					),
				),
				array(
					'key' => 'field_6100fd5b5d7d1',
					'label' => 'Advanced Filters',
					'name' => 'advanced_filters',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'layout' => 'block',
					'acfe_group_modal' => 1,
					'acfe_group_modal_close' => 1,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
					'acfe_seamless_style' => 0,
					'parent_repeater' => 'field_6100fea589d3a',
					'sub_fields' => array(
						array(
							'key' => 'field_6100fd785d7d2',
							'label' => 'Max Per Post',
							'name' => 'max_per_post',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => 'Set to 0 for no limit on number of ads per post.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'default_value' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 10,
							'step' => 1,
						),
						array(
							'key' => 'field_6100fdc45d7d3',
							'label' => 'Posts to Include',
							'name' => 'posts_to_include',
							'aria-label' => '',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'post_type' => array(
								0 => 'editorial',
							),
							'taxonomy' => '',
							'allow_null' => 1,
							'multiple' => 1,
							'return_format' => 'object',
							'save_custom' => 0,
							'save_post_status' => 'publish',
							'acfe_bidirectional' => array(
								'acfe_bidirectional_enabled' => '0',
							),
							'ui' => 1,
							'save_post_type' => '',
							'acfe_add_post' => 0,
							'acfe_edit_post' => 0,
							'min' => '',
							'max' => '',
							'bidirectional_target' => array(
							),
						),
						array(
							'key' => 'field_6100fe2a5d7d4',
							'label' => 'Posts to Exclude',
							'name' => 'posts_to_exclude',
							'aria-label' => '',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'post_type' => array(
								0 => 'editorial',
							),
							'taxonomy' => '',
							'allow_null' => 1,
							'multiple' => 1,
							'return_format' => 'object',
							'save_custom' => 0,
							'save_post_status' => 'publish',
							'acfe_bidirectional' => array(
								'acfe_bidirectional_enabled' => '0',
							),
							'ui' => 1,
							'save_post_type' => '',
							'acfe_add_post' => 0,
							'acfe_edit_post' => 0,
							'min' => '',
							'max' => '',
							'bidirectional_target' => array(
							),
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'inline-ad-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'show_in_graphql' => 0,
	'graphql_field_name' => 'inlineAdSettings',
	'map_graphql_types_from_location_rules' => 1,
	'graphql_types' => '',
	'modified' => 1721905345,
));

endif;